export const tailwindCustomProseClass =
  "prose prose-lg prose-p:font-light prose-h1:font-semibold prose-h2:font-semibold prose-a:font-light prose-ol:font-light prose-ul:font-light prose-li:font-light prose-code:font-light prose-blockquote:font-light";

export const randomJobData = {
  title: {
    prefix: [
      "Senior",
      "Junior",
      "Lead",
      "Principal",
      "Associate",
      "Chief",
      "Executive",
      "Entry-level",
      "Social Media",
      // "Influencer",
    ],
    middle: [
      "Software",
      "Finance",
      "Human Resources",
      "Marketing",
      "Data",
      "Customer Service",
      "Operations",
      "Research",
      "Quality Assurance",
      "Project",
      "Product",
      // "TikTok",
      // "Gaming",
      // "Streaming",
      // "Your Mom",
    ],
    suffix: [
      "Developer",
      "Engineer",
      "Analyst",
      "Specialist",
      "Manager",
      "Director",
      "Consultant",
      "Coordinator",
      "Administrator",
      "Strategist",
      "Officer",
      "Representative",
      "Designer",
      // "Guru",
      // "Ninja",
    ],
  },
  description: [
    "This job requires thinking outside the box. ",
    "Join our team and be part of something big! ",
    "We're looking for someone who loves challenges. ",
    "Are you ready to make a difference? ",
    "Join us in shaping the future of our organisation. ",
    "Experience the thrill of innovation every day. ",
    "# Markdown description: _Exciting opportunities await!_ ",
    "This role will test your problem-solving skills to the limit. ",
    "Collaborate with the best minds in the industry. ",
    "We're not just a company; we're a family. ",
    "Be prepared to tackle new challenges head-on. ",
    "Make your mark in the world of academia. ",
    "Transform ideas into reality with us. ",
    "Join a dynamic team with endless possibilities. ",
    // "Flex your meme-making skills and help us go viral! ",
    // "Get ready to slay the digital world with us. ",
    // "Embrace the power of social media in this role. ",
    // "Unleash your inner influencer and join our team. ",
    // "This job is more lit than your favorite meme! ",
    // "Turn your passion for gaming into a career. ",
    // "Join us on the cutting edge of internet culture. ",
    // "This role will make you say 'BRB, gotta update my status.' ",
    // "Work hard, play hard, meme hard. ",
    "Imagine a workplace where your ideas matter, where innovation is celebrated, and where your potential is limitless. Welcome to our team!",
    "In this role, you'll embark on a journey of discovery, pushing the boundaries of what's possible and redefining excellence every step of the way.",
    "Do you thrive in fast-paced environments? Are you fueled by creativity and driven by results? Join us and be part of a revolution in academia.",
    "Join our vibrant community of thinkers, doers, and dreamers. Together, we'll shape the future and inspire generations to come.",
    "Are you ready to embark on an adventure in innovation and discovery? Join us and unleash your full potential!",
    "Join a team where every day brings new challenges and opportunities for growth. Your journey starts here.",
    "This isn't just a job; it's a chance to make a meaningful impact on the world. Are you up for the challenge?",
    "Do you have what it takes to be a part of our dynamic team? Apply now and let's build something incredible together!",
    "Looking for a role that combines passion with purpose? Join us and be part of a movement that's changing lives.",
    "We're on a mission to revolutionise the industry. Are you ready to be a trailblazer?",
    "Join us and be at the forefront of innovation, shaping the future one breakthrough at a time.",
    "Calling all visionaries, problem-solvers, and change-makers! Your next adventure awaits.",
    "Ready to take the leap into the unknown? Join our team and let's explore new horizons together.",
    "At the intersection of passion and opportunity lies your next career move. Join us and let's create something extraordinary.",
    // "Tired of adulting? Join our team and let's pretend to be responsible together!",
    // "Looking for a job that doesn't suck the life out of you? Well, ours might, but at least we have free coffee!",
    // "Join us and discover the true meaning of 'working hard'... or hardly working, we won't judge.",
    // "Sick of corporate BS? Us too! Join our team and let's make inappropriate jokes in the break room.",
    // "If you're looking for a job that's a total joke, you've come to the right place. Apply now and let's laugh our way to the bank!",
    // "Warning: This job may cause excessive drinking. But hey, at least it's on the company's tab!",
    // "Join our dysfunctional family and experience the joys of passive-aggressive emails and awkward office parties.",
    // "Looking for a job with zero accountability? Congratulations, you've found it!",
    // "At our company, we don't just break the rules; we make our own. Apply now and let's see how much trouble we can get into together!",
    // "Need a job that's more fun than therapy? Look no further. Apply now and let the healing begin!",
    // "Are you fucking tired of your current job? Us too. Apply now and let's bitch about it together over drinks.",
    // "Looking for a job that doesn't make you want to stab yourself in the eye with a pencil? You've come to the right fucking place.",
    // "Join our team and experience the thrill of pretending to give a shit about meaningless tasks. It's fucking exhilarating.",
    // "Tired of working with assholes? So are we. Apply now and let's build a team of fucking rockstars.",
    // "If you're fucking awesome and tired of working with mediocre assholes, we want you on our team.",
    // "Ready to kick some fucking ass in your career? Apply now and let's dominate the fucking world together.",
    // "Looking for a job that doesn't make you want to punch someone in the face? Sorry, can't help you there. But we do have great benefits!",
    // "Join our team of misfits, rebels, and fucking geniuses. Together, we'll conquer the fucking universe.",
    // "Sick of corporate bullshit? Us too. Apply now and let's burn this motherfucker down.",
    // "Want a job where you can tell your boss to go fuck themselves? Well, you can't do that here. But we do have free snacks!",
    "Looking for a job where you can *flex* your coding muscles and unleash your creativity? Join our team and let's **innovate** together! From brainstorming sessions to late-night coding marathons, we're all about pushing the boundaries of what's possible. *Apply now* and let's create something *epic*. ",
    "Are you ready to embark on an adventure in **data analysis**? Join us and dive deep into the world of *big data*, where every byte tells a story. From crunching numbers to uncovering hidden insights, this role is all about turning data into **actionable intelligence**. *Apply now* and let's make some **data magic** happen! ",
    "Do you have a passion for **design** and an eye for detail? Join our team and let's bring your creative visions to life! From wireframes to mockups, we're all about crafting **beautiful** and **intuitive** user experiences. *Apply now* and let's design the next **big thing** together! ",
    "Looking for a job where you can *lead* from the front and drive results? Join us and step into the role of **project manager extraordinaire**! From coordinating timelines to motivating teams, this role is all about **getting shit done**. *Apply now* and let's make some **project magic** happen! ",
    "Are you a **problem-solving** guru with a knack for **code optimisation**? Join our team and let's tackle some of the toughest coding challenges together! From debugging to performance tuning, this role is all about making our code **leaner**, **meaner**, and **faster**. *Apply now* and let's optimise the world, one line of code at a time! ",
  ],
  faculty: [
    "Arts and Humanities",
    "Business and Law",
    "Environmental and Life Sciences",
    "Medicine",
    "Social Sciences",
    "Engineering and Technology",
    "Education",
    "Health Sciences",
    "Physical Sciences",
    "Information Sciences",
    // "Agricultural Sciences",
  ],
  department: [
    "Department of Drama",
    "Department of English",
    "Department of Finance",
    "Department of Computer Science",
    "Department of Engineering",
    // "Department of Quantum Physics",
    // "Department of Memes and Internet Studies",
    // "Department of Astrobiology",
    // "Department of Paranormal Research",
    // "Department of Adventure Planning",
    // "Department of Space Exploration",
    // "Department of Exotic Pet Care",
    // "Department of Culinary Arts",
    // "Department of Wilderness Survival",
    // "Department of Getting Zero Bitches",
  ],
  tags: [
    "React",
    "Typescript",
    "Low-Pressure",
    "High-Stress",
    "Travel",
    "Remote",
    "Flexible Hours",
    "Teamwork",
    "Innovation",
    "Creativity",
    "Problem-solving",
    "Leadership",
    "Multitasking",
    "Adaptability",
    // "Viral",
    // "Trending",
    // "Lit",
    // "Slaying",
    // "BRB",
    // "Meme Master",
    // "Gaming Guru",
  ],
  location: [
    "University of Sheffield",
    "Sheffield",

    // "Silicon Valley",
    // "New York City",
    // "Los Angeles",
    // "London",
    // "Tokyo",
    // "Paris",
    // "Berlin",
    // "Sydney",
    // "Seattle",
  ],
};
